version: '3'

services:
  web:
    build: .
    command: gunicorn blog_api_project.wsgi:application --bind 0.0.0.0:8000 --workers 4
    volumes:
      - .:/code
    ports:
      - "8000:8000"
#     depends_on:
#       - db
#   db:
#     image: postgres:11
#     volumes:
#       - postgres_data:/var/lib/postgresql/data/
#     environment:
#       - POSTGRES_DB=${POSTGRES_DB}
#       - POSTGRES_USER=${POSTGRES_USER}
#       - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
# volumes:
#     postgres_data:
